version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "numpy"
        versions: [">=2.0.0"]
