name: dependabot-auto-merge
on:
  pull_request_target:
    types: [opened, edited, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge minor/patch when green
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
