name: pre-commit
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  pre-commit:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure
